title: Tianyi Xie
logo: /assets/img/tianyixie3.JPG
description: CS PhD student at UCLA (Photo credit to <a href="https://yingjiang96.github.io/">Ying Jiang</a>)
email: tianyixie77@g.ucla.edu
favicon: true
color-scheme: light

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/XPandora
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/tianyi-xie-784230189/
  - name: Google Scholar
    icon: <i class="fa-brands fa-google"></i>
    link: https://scholar.google.com/citations?user=oRt4qcgAAAAJ&hl=en
  - name: Resume
    icon: <i class="fa-solid fa-file"></i>
    link: ./assets/file/Tianyi_Xie_CV_(2024_08).pdf

# navigation:
#   - name: Readme
#     link: ./index.html
#     sublist:
#       - name: Image
#         link: ./index.html#small-image
#   - name: Another Page
#     link: ./another-page.html

remote_theme: vaibhavvikas/jekyll-theme-minimalistic
